version: '3.7'
services:
  postgres:
    # 11-alpine
    image: postgres:11-alpine
    container_name: globe42-postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    # copying the database.sql file in the /docker-entrypoint-initdb.d/ directory
    # the script run on start by the postgres container
    # and creates the appropriate databases and users
    volumes:
      - ./backend/database:/docker-entrypoint-initdb.d/:cached
    ports:
      - 5432:5432

