version: '3.7'
services:
  postgres:
    # 11-alpine
    image: postgres@sha256:fdecfb9a2de3bd27ca695cecb79b4519b74f7c9e505fa4f9129a9e72e8ff5193
    container_name: globe42-postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    # copying the database.sql file in the /docker-entrypoint-initdb.d/ directory
    # the script run on start by the postgres container
    # and creates the appropriate databases and users
    volumes:
      - ./backend/database:/docker-entrypoint-initdb.d/:cached
    ports:
      - 5432:5432

