package org.globe42.domain;

import java.time.LocalDate;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.validation.Valid;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

/**
 * A person helped by, or member of Globe 42.
 * There are two main kinds of persons. Those for whom mediation is done by Globe 42, and the others.
 * For those who have mediation enabled, a mediation code is generated by the application, and several additional
 * fields are requested about them.
 * @author JB Nizet
 */
@Entity
public class Person {

    private static final String PERSON_GENERATOR = "PersonGenerator";

    @Id
    @SequenceGenerator(name = PERSON_GENERATOR, sequenceName = "PERSON_SEQ", initialValue = 1000, allocationSize = 1)
    @GeneratedValue(generator = PERSON_GENERATOR)
    private Long id;

    /**
     * The first name, requested to all persons, and mandatory
     */
    @NotEmpty
    private String firstName;

    /**
     * The last name, requested to all persons, and mandatory
     */
    @NotEmpty
    private String lastName;

    /**
     * The nick name, requested to all persons, but not mandatory
     */
    private String nickName;

    /**
     * The gender of the person, requested to all persons, and mandatory
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    private Gender gender;

    /**
     * The birth date, requested to all persons, but not mandatory
     */
    private LocalDate birthDate;

    /**
     * Is the person an official member of the association. Requested to all persons, and mandatory.
     */
    private boolean adherent;

    /**
     * The first address line (street and number, typically) of the person. Requested to all persons, but not mandatory
     */
    private String address;

    /**
     * The postal code and city of the person. Requested to all persons, but not mandatory
     */
    @Embedded
    @Valid
    private City city;

    /**
     * The email of the person. Requested to all persons, but not mandatory
     */
    @Email
    private String email;

    /**
     * The phone number of the person. Requested to all persons, but not mandatory
     */
    private String phoneNumber;

    /**
     * The name of individual who accompanies the person. Requested to all persons, but not mandatory
     */
    private String attendant;

    /**
     * Is mediation enabled for the person or not. Requested to all persons, and mandatory.
     */
    private boolean mediationEnabled;

    /**
     * The mediation code, generated automatically for mediation-enabled persons only, from the first letter of the
     * last name, and from a sequence.
     */
    private String mediationCode;

    /**
     * The date of entry in France. Only requested to mediation-enabled persons, but not mandatory
     */
    private LocalDate entryDate;

    /**
     * The marital status. Only requested to mediation-enabled persons, and unknown by default (so, technically
     * mandatory, but can be left as unknown)
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    private MaritalStatus maritalStatus = MaritalStatus.UNKNOWN;

    /**
     * The housing kind. Only requested to mediation-enabled persons, and unknown by default (so, technically
     * mandatory, but can be left as unknown)
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    private Housing housing = Housing.UNKNOWN;

    /**
     * The housing space, in square meters. Only requested to mediation-enabled persons, and not mandatory
     */
    private Integer housingSpace;

    /**
     * The fiscal status. Only requested to mediation-enabled persons, and unknown by default (so, technically
     * mandatory, but can be left as unknown)
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    private FiscalStatus fiscalStatus = FiscalStatus.UNKNOWN;

    /**
     * The date when the fiscal statuswas established. Only requested to mediation-enabled persons, if the fiscal
     * status is not {@link FiscalStatus#UNKNOWN}.
     */
    private LocalDate fiscalStatusDate;

    /**
     * Is the fiscal status up-to-date. Only requested to mediation-enabled persons, if the fiscal
     * status is not {@link FiscalStatus#UNKNOWN}.
     */
    private boolean fiscalStatusUpToDate;

    /**
     * The family situation of the person in France. Only requested to mediation-enabled persons, and not mandatory
     */
    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private FamilySituation frenchFamilySituation;

    /**
     * The family situation of the person abroad. Only requested to mediation-enabled persons, and not mandatory
     */
    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private FamilySituation abroadFamilySituation;

    /**
     * The incomes of the person. Only requested to mediation-enabled persons
     */
    @OneToMany(mappedBy = "person", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Income> incomes = new HashSet<>();

    /**
     * The charges of the person. Only requested to mediation-enabled persons
     */
    @OneToMany(mappedBy = "person", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Charge> charges = new HashSet<>();

    /**
     * The Health Care Coverage. Only requested to mediation-enabled persons, and unknown by default (so, technically
     * mandatory, but can be left as unknown)
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    private HealthCareCoverage healthCareCoverage = HealthCareCoverage.UNKNOWN;

    /**
     * The notes added on the person
     */
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
    @JoinTable(name = "person_note",
        joinColumns = @JoinColumn(name = "person_id"),
        inverseJoinColumns = @JoinColumn(name = "note_id")
    )
    private Set<Note> notes = new HashSet<>();

    /**
     * The participations to activity types of the person
     */
    @OneToMany(mappedBy = "person", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Participation> participations = new HashSet<>();

    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public LocalDate getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    public boolean isAdherent() {
        return adherent;
    }

    public void setAdherent(boolean adherent) {
        this.adherent = adherent;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getAttendant() { return attendant; }

    public void setAttendant(String attendant) { this.attendant = attendant; }

    public boolean isMediationEnabled() {
        return mediationEnabled;
    }

    public void setMediationEnabled(boolean mediationEnabled) {
        this.mediationEnabled = mediationEnabled;
    }

    public String getMediationCode() {
        return mediationCode;
    }

    public void setMediationCode(String mediationCode) {
        this.mediationCode = mediationCode;
    }

    public LocalDate getEntryDate() {
        return entryDate;
    }

    public void setEntryDate(LocalDate entryDate) {
        this.entryDate = entryDate;
    }

    public MaritalStatus getMaritalStatus() {
        return maritalStatus;
    }

    public void setMaritalStatus(MaritalStatus maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    public Housing getHousing() {
        return housing;
    }

    public void setHousing(Housing housing) {
        this.housing = housing;
    }

    public Integer getHousingSpace() {
        return housingSpace;
    }

    public void setHousingSpace(Integer housingSpace) {
        this.housingSpace = housingSpace;
    }

    public FiscalStatus getFiscalStatus() {
        return fiscalStatus;
    }

    public void setFiscalStatus(FiscalStatus fiscalStatus) {
        this.fiscalStatus = fiscalStatus;
    }

    public LocalDate getFiscalStatusDate() {
        return fiscalStatusDate;
    }

    public void setFiscalStatusDate(LocalDate fiscalStatusDate) {
        this.fiscalStatusDate = fiscalStatusDate;
    }

    public boolean isFiscalStatusUpToDate() {
        return fiscalStatusUpToDate;
    }

    public void setFiscalStatusUpToDate(boolean fiscalStatusUpToDate) {
        this.fiscalStatusUpToDate = fiscalStatusUpToDate;
    }

    public FamilySituation getFrenchFamilySituation() {
        return frenchFamilySituation;
    }

    public void setFrenchFamilySituation(FamilySituation frenchFamilySituation) {
        this.frenchFamilySituation = frenchFamilySituation;
    }

    public FamilySituation getAbroadFamilySituation() {
        return abroadFamilySituation;
    }

    public void setAbroadFamilySituation(FamilySituation abroadFamilySituation) {
        this.abroadFamilySituation = abroadFamilySituation;
    }

    public void addIncome(Income income) {
        income.setPerson(this);
        this.incomes.add(income);
    }

    public void removeIncome(Income income) {
        income.setPerson(null);
        this.incomes.remove(income);
    }

    public Set<Income> getIncomes() {
        return Collections.unmodifiableSet(incomes);
    }

    public void addCharge(Charge charge) {
        charge.setPerson(this);
        this.charges.add(charge);
    }

    public void removeCharge(Charge charge) {
        charge.setPerson(null);
        this.charges.remove(charge);
    }

    public Set<Charge> getCharges() {
        return Collections.unmodifiableSet(charges);
    }

    public HealthCareCoverage getHealthCareCoverage() {
        return healthCareCoverage;
    }

    public void setHealthCareCoverage(HealthCareCoverage healthCareCoverage) {
        this.healthCareCoverage = healthCareCoverage;
    }

    public Set<Note> getNotes() {
        return Collections.unmodifiableSet(notes);
    }

    public void addNote(Note note) {
        this.notes.add(note);
    }

    public void removeNote(Note note) {
        this.notes.remove(note);
    }

    public Set<Participation> getParticipations() {
        return Collections.unmodifiableSet(participations);
    }

    public void addParticipation(Participation participation) {
        participation.setPerson(this);
        participations.add(participation);
    }

    public void removeParticipation(Participation participation) {
        participations.remove(participation);
    }
}
