version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:

    working_directory: ~/globe42

    docker:
      - image: cimg/openjdk:11.0-browsers
      - image: circleci/postgres:11.1-alpine-ram

    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: psql -h localhost -f backend/database/database.sql -U postgres
      - run: ./gradlew build jacocoTestReport --parallel
      - run: ./gradlew :frontend:yarnCodecov :frontend:yarnBundlesize
