CREATE TABLE country (
  id VARCHAR(3) PRIMARY KEY,
  name VARCHAR UNIQUE
);

ALTER TABLE person
  ADD COLUMN nationality_id VARCHAR(3);
ALTER TABLE person
  ADD CONSTRAINT person_fk4 FOREIGN KEY (nationality_id) REFERENCES country (id);

INSERT INTO country (id, name) VALUES ('ABW', 'Aruba');
INSERT INTO country (id, name) VALUES ('AFG', 'Afghanistan');
INSERT INTO country (id, name) VALUES ('AGO', 'Angola');
INSERT INTO country (id, name) VALUES ('AIA', 'Anguilla');
INSERT INTO country (id, name) VALUES ('ALA', 'Åland');
INSERT INTO country (id, name) VALUES ('ALB', 'Albanie');
INSERT INTO country (id, name) VALUES ('AND', 'Andorre');
INSERT INTO country (id, name) VALUES ('ARE', 'Émirats arabes unis');
INSERT INTO country (id, name) VALUES ('ARG', 'Argentine');
INSERT INTO country (id, name) VALUES ('ARM', 'Arménie');
INSERT INTO country (id, name) VALUES ('ASM', 'Samoa américaines');
INSERT INTO country (id, name) VALUES ('ATA', 'Antarctique');
INSERT INTO country (id, name) VALUES ('ATF', 'Terres australes françaises');
INSERT INTO country (id, name) VALUES ('ATG', 'Antigua-et-Barbuda');
INSERT INTO country (id, name) VALUES ('AUS', 'Australie');
INSERT INTO country (id, name) VALUES ('AUT', 'Autriche');
INSERT INTO country (id, name) VALUES ('AZE', 'Azerbaïdjan');
INSERT INTO country (id, name) VALUES ('BDI', 'Burundi');
INSERT INTO country (id, name) VALUES ('BEL', 'Belgique');
INSERT INTO country (id, name) VALUES ('BEN', 'Bénin');
INSERT INTO country (id, name) VALUES ('BES', 'Bonaire, Saint-Eustache et Saba');
INSERT INTO country (id, name) VALUES ('BFA', 'Burkina Faso');
INSERT INTO country (id, name) VALUES ('BGD', 'Bangladesh');
INSERT INTO country (id, name) VALUES ('BGR', 'Bulgarie');
INSERT INTO country (id, name) VALUES ('BHR', 'Bahreïn');
INSERT INTO country (id, name) VALUES ('BHS', 'Bahamas');
INSERT INTO country (id, name) VALUES ('BIH', 'Bosnie-Herzégovine');
INSERT INTO country (id, name) VALUES ('BLM', 'Saint-Barthélemy');
INSERT INTO country (id, name) VALUES ('BLR', 'Bélarus');
INSERT INTO country (id, name) VALUES ('BLZ', 'Belize');
INSERT INTO country (id, name) VALUES ('BMU', 'Bermudes');
INSERT INTO country (id, name) VALUES ('BOL', 'Bolivie');
INSERT INTO country (id, name) VALUES ('BRA', 'Brésil');
INSERT INTO country (id, name) VALUES ('BRB', 'Barbade');
INSERT INTO country (id, name) VALUES ('BRN', 'Brunéi Darussalam');
INSERT INTO country (id, name) VALUES ('BTN', 'Bhoutan');
INSERT INTO country (id, name) VALUES ('BVT', 'Bouvet');
INSERT INTO country (id, name) VALUES ('BWA', 'Botswana');
INSERT INTO country (id, name) VALUES ('CAF', 'République centrafricaine');
INSERT INTO country (id, name) VALUES ('CAN', 'Canada');
INSERT INTO country (id, name) VALUES ('CCK', 'Cocos');
INSERT INTO country (id, name) VALUES ('CHE', 'Suisse');
INSERT INTO country (id, name) VALUES ('CHL', 'Chili');
INSERT INTO country (id, name) VALUES ('CHN', 'Chine');
INSERT INTO country (id, name) VALUES ('CIV', 'Côte d''Ivoire');
INSERT INTO country (id, name) VALUES ('CMR', 'Cameroun');
INSERT INTO country (id, name) VALUES ('COD', 'Congo (République démocratique du)');
INSERT INTO country (id, name) VALUES ('COG', 'Congo');
INSERT INTO country (id, name) VALUES ('COK', 'Cook');
INSERT INTO country (id, name) VALUES ('COL', 'Colombie');
INSERT INTO country (id, name) VALUES ('COM', 'Comores');
INSERT INTO country (id, name) VALUES ('CPV', 'Cabo Verde');
INSERT INTO country (id, name) VALUES ('CRI', 'Costa Rica');
INSERT INTO country (id, name) VALUES ('CUB', 'Cuba');
INSERT INTO country (id, name) VALUES ('CUW', 'Curaçao');
INSERT INTO country (id, name) VALUES ('CXR', 'Christmas');
INSERT INTO country (id, name) VALUES ('CYM', 'Caïmans');
INSERT INTO country (id, name) VALUES ('CYP', 'Chypre');
INSERT INTO country (id, name) VALUES ('CZE', 'Tchéquie');
INSERT INTO country (id, name) VALUES ('DEU', 'Allemagne');
INSERT INTO country (id, name) VALUES ('DJI', 'Djibouti');
INSERT INTO country (id, name) VALUES ('DMA', 'Dominique');
INSERT INTO country (id, name) VALUES ('DNK', 'Danemark');
INSERT INTO country (id, name) VALUES ('DOM', 'dominicaine');
INSERT INTO country (id, name) VALUES ('DZA', 'Algérie');
INSERT INTO country (id, name) VALUES ('ECU', 'Équateur');
INSERT INTO country (id, name) VALUES ('EGY', 'Égypte');
INSERT INTO country (id, name) VALUES ('ERI', 'Érythrée');
INSERT INTO country (id, name) VALUES ('ESH', 'Sahara occidental *');
INSERT INTO country (id, name) VALUES ('ESP', 'Espagne');
INSERT INTO country (id, name) VALUES ('EST', 'Estonie');
INSERT INTO country (id, name) VALUES ('ETH', 'Éthiopie');
INSERT INTO country (id, name) VALUES ('FIN', 'Finlande');
INSERT INTO country (id, name) VALUES ('FJI', 'Fidji');
INSERT INTO country (id, name) VALUES ('FLK', 'Falkland');
INSERT INTO country (id, name) VALUES ('FRA', 'France');
INSERT INTO country (id, name) VALUES ('FRO', 'Féroé');
INSERT INTO country (id, name) VALUES ('FSM', 'Micronésie');
INSERT INTO country (id, name) VALUES ('GAB', 'Gabon');
INSERT INTO country (id, name) VALUES ('GBR', 'Royaume-Uni de Grande-Bretagne et d''Irlande du Nord');
INSERT INTO country (id, name) VALUES ('GEO', 'Géorgie');
INSERT INTO country (id, name) VALUES ('GGY', 'Guernesey');
INSERT INTO country (id, name) VALUES ('GHA', 'Ghana');
INSERT INTO country (id, name) VALUES ('GIB', 'Gibraltar');
INSERT INTO country (id, name) VALUES ('GIN', 'Guinée');
INSERT INTO country (id, name) VALUES ('GLP', 'Guadeloupe');
INSERT INTO country (id, name) VALUES ('GMB', 'Gambie');
INSERT INTO country (id, name) VALUES ('GNB', 'Guinée-Bissau');
INSERT INTO country (id, name) VALUES ('GNQ', 'Guinée équatoriale');
INSERT INTO country (id, name) VALUES ('GRC', 'Grèce');
INSERT INTO country (id, name) VALUES ('GRD', 'Grenade');
INSERT INTO country (id, name) VALUES ('GRL', 'Groenland');
INSERT INTO country (id, name) VALUES ('GTM', 'Guatemala');
INSERT INTO country (id, name) VALUES ('GUF', 'Guyane française');
INSERT INTO country (id, name) VALUES ('GUM', 'Guam');
INSERT INTO country (id, name) VALUES ('GUY', 'Guyana');
INSERT INTO country (id, name) VALUES ('HKG', 'Hong Kong');
INSERT INTO country (id, name) VALUES ('HMD', 'Heard-et-Îles MacDonald');
INSERT INTO country (id, name) VALUES ('HND', 'Honduras');
INSERT INTO country (id, name) VALUES ('HRV', 'Croatie');
INSERT INTO country (id, name) VALUES ('HTI', 'Haïti');
INSERT INTO country (id, name) VALUES ('HUN', 'Hongrie');
INSERT INTO country (id, name) VALUES ('IDN', 'Indonésie');
INSERT INTO country (id, name) VALUES ('IMN', 'Île de Man');
INSERT INTO country (id, name) VALUES ('IND', 'Inde');
INSERT INTO country (id, name) VALUES ('IOT', 'Indien');
INSERT INTO country (id, name) VALUES ('IRL', 'Irlande');
INSERT INTO country (id, name) VALUES ('IRN', 'Iran');
INSERT INTO country (id, name) VALUES ('IRQ', 'Iraq');
INSERT INTO country (id, name) VALUES ('ISL', 'Islande');
INSERT INTO country (id, name) VALUES ('ISR', 'Israël');
INSERT INTO country (id, name) VALUES ('ITA', 'Italie');
INSERT INTO country (id, name) VALUES ('JAM', 'Jamaïque');
INSERT INTO country (id, name) VALUES ('JEY', 'Jersey');
INSERT INTO country (id, name) VALUES ('JOR', 'Jordanie');
INSERT INTO country (id, name) VALUES ('JPN', 'Japon');
INSERT INTO country (id, name) VALUES ('KAZ', 'Kazakhstan');
INSERT INTO country (id, name) VALUES ('KEN', 'Kenya');
INSERT INTO country (id, name) VALUES ('KGZ', 'Kirghizistan');
INSERT INTO country (id, name) VALUES ('KHM', 'Cambodge');
INSERT INTO country (id, name) VALUES ('KIR', 'Kiribati');
INSERT INTO country (id, name) VALUES ('KNA', 'Saint-Kitts-et-Nevis');
INSERT INTO country (id, name) VALUES ('KOR', 'Corée (République de)');
INSERT INTO country (id, name) VALUES ('KWT', 'Koweït');
INSERT INTO country (id, name) VALUES ('LAO', 'Lao, République démocratique populaire');
INSERT INTO country (id, name) VALUES ('LBN', 'Liban');
INSERT INTO country (id, name) VALUES ('LBR', 'Libéria');
INSERT INTO country (id, name) VALUES ('LBY', 'Libye');
INSERT INTO country (id, name) VALUES ('LCA', 'Sainte-Lucie');
INSERT INTO country (id, name) VALUES ('LIE', 'Liechtenstein');
INSERT INTO country (id, name) VALUES ('LKA', 'Sri Lanka');
INSERT INTO country (id, name) VALUES ('LSO', 'Lesotho');
INSERT INTO country (id, name) VALUES ('LTU', 'Lituanie');
INSERT INTO country (id, name) VALUES ('LUX', 'Luxembourg');
INSERT INTO country (id, name) VALUES ('LVA', 'Lettonie');
INSERT INTO country (id, name) VALUES ('MAC', 'Macao');
INSERT INTO country (id, name) VALUES ('MAF', 'Saint-Martin (partie française)');
INSERT INTO country (id, name) VALUES ('MAR', 'Maroc');
INSERT INTO country (id, name) VALUES ('MCO', 'Monaco');
INSERT INTO country (id, name) VALUES ('MDA', 'Moldova, République de');
INSERT INTO country (id, name) VALUES ('MDG', 'Madagascar');
INSERT INTO country (id, name) VALUES ('MDV', 'Maldives');
INSERT INTO country (id, name) VALUES ('MEX', 'Mexique');
INSERT INTO country (id, name) VALUES ('MHL', 'Marshall');
INSERT INTO country (id, name) VALUES ('MKD', 'Macédoine');
INSERT INTO country (id, name) VALUES ('MLI', 'Mali');
INSERT INTO country (id, name) VALUES ('MLT', 'Malte');
INSERT INTO country (id, name) VALUES ('MMR', 'Myanmar');
INSERT INTO country (id, name) VALUES ('MNE', 'Monténégro');
INSERT INTO country (id, name) VALUES ('MNG', 'Mongolie');
INSERT INTO country (id, name) VALUES ('MNP', 'Mariannes du Nord');
INSERT INTO country (id, name) VALUES ('MOZ', 'Mozambique');
INSERT INTO country (id, name) VALUES ('MRT', 'Mauritanie');
INSERT INTO country (id, name) VALUES ('MSR', 'Montserrat');
INSERT INTO country (id, name) VALUES ('MTQ', 'Martinique');
INSERT INTO country (id, name) VALUES ('MUS', 'Maurice');
INSERT INTO country (id, name) VALUES ('MWI', 'Malawi');
INSERT INTO country (id, name) VALUES ('MYS', 'Malaisie');
INSERT INTO country (id, name) VALUES ('MYT', 'Mayotte');
INSERT INTO country (id, name) VALUES ('NAM', 'Namibie');
INSERT INTO country (id, name) VALUES ('NCL', 'Nouvelle-Calédonie');
INSERT INTO country (id, name) VALUES ('NER', 'Niger');
INSERT INTO country (id, name) VALUES ('NFK', 'Norfolk');
INSERT INTO country (id, name) VALUES ('NGA', 'Nigéria');
INSERT INTO country (id, name) VALUES ('NIC', 'Nicaragua');
INSERT INTO country (id, name) VALUES ('NIU', 'Niue');
INSERT INTO country (id, name) VALUES ('NLD', 'Pays-Bas');
INSERT INTO country (id, name) VALUES ('NOR', 'Norvège');
INSERT INTO country (id, name) VALUES ('NPL', 'Népal');
INSERT INTO country (id, name) VALUES ('NRU', 'Nauru');
INSERT INTO country (id, name) VALUES ('NZL', 'Nouvelle-Zélande');
INSERT INTO country (id, name) VALUES ('OMN', 'Oman');
INSERT INTO country (id, name) VALUES ('PAK', 'Pakistan');
INSERT INTO country (id, name) VALUES ('PAN', 'Panama');
INSERT INTO country (id, name) VALUES ('PCN', 'Pitcairn');
INSERT INTO country (id, name) VALUES ('PER', 'Pérou');
INSERT INTO country (id, name) VALUES ('PHL', 'Philippines');
INSERT INTO country (id, name) VALUES ('PLW', 'Palaos');
INSERT INTO country (id, name) VALUES ('PNG', 'Papouasie-Nouvelle-Guinée');
INSERT INTO country (id, name) VALUES ('POL', 'Pologne');
INSERT INTO country (id, name) VALUES ('PRI', 'Porto Rico');
INSERT INTO country (id, name) VALUES ('PRK', 'Corée (République populaire démocratique de)');
INSERT INTO country (id, name) VALUES ('PRT', 'Portugal');
INSERT INTO country (id, name) VALUES ('PRY', 'Paraguay');
INSERT INTO country (id, name) VALUES ('PSE', 'Palestine, État de');
INSERT INTO country (id, name) VALUES ('PYF', 'Polynésie française');
INSERT INTO country (id, name) VALUES ('QAT', 'Qatar');
INSERT INTO country (id, name) VALUES ('REU', 'Réunion');
INSERT INTO country (id, name) VALUES ('ROU', 'Roumanie');
INSERT INTO country (id, name) VALUES ('RUS', 'Russie');
INSERT INTO country (id, name) VALUES ('RWA', 'Rwanda');
INSERT INTO country (id, name) VALUES ('SAU', 'Arabie saoudite');
INSERT INTO country (id, name) VALUES ('SDN', 'Soudan');
INSERT INTO country (id, name) VALUES ('SEN', 'Sénégal');
INSERT INTO country (id, name) VALUES ('SGP', 'Singapour');
INSERT INTO country (id, name) VALUES ('SGS', 'Géorgie du Sud-et-les Îles Sandwich du Sud');
INSERT INTO country (id, name) VALUES ('SHN', 'Sainte-Hélène, Ascension et Tristan da Cunha');
INSERT INTO country (id, name) VALUES ('SJM', 'Svalbard et l''Île Jan Mayen');
INSERT INTO country (id, name) VALUES ('SLB', 'Salomon');
INSERT INTO country (id, name) VALUES ('SLE', 'Sierra Leone');
INSERT INTO country (id, name) VALUES ('SLV', 'El Salvador');
INSERT INTO country (id, name) VALUES ('SMR', 'Saint-Marin');
INSERT INTO country (id, name) VALUES ('SOM', 'Somalie');
INSERT INTO country (id, name) VALUES ('SPM', 'Saint-Pierre-et-Miquelon');
INSERT INTO country (id, name) VALUES ('SRB', 'Serbie');
INSERT INTO country (id, name) VALUES ('SSD', 'Soudan du Sud');
INSERT INTO country (id, name) VALUES ('STP', 'Sao Tomé-et-Principe');
INSERT INTO country (id, name) VALUES ('SUR', 'Suriname');
INSERT INTO country (id, name) VALUES ('SVK', 'Slovaquie');
INSERT INTO country (id, name) VALUES ('SVN', 'Slovénie');
INSERT INTO country (id, name) VALUES ('SWE', 'Suède');
INSERT INTO country (id, name) VALUES ('SWZ', 'Swaziland');
INSERT INTO country (id, name) VALUES ('SXM', 'Saint-Martin (partie néerlandaise)');
INSERT INTO country (id, name) VALUES ('SYC', 'Seychelles');
INSERT INTO country (id, name) VALUES ('SYR', 'République arabe syrienne');
INSERT INTO country (id, name) VALUES ('TCA', 'Turks-et-Caïcos');
INSERT INTO country (id, name) VALUES ('TCD', 'Tchad');
INSERT INTO country (id, name) VALUES ('TGO', 'Togo');
INSERT INTO country (id, name) VALUES ('THA', 'Thaïlande');
INSERT INTO country (id, name) VALUES ('TJK', 'Tadjikistan');
INSERT INTO country (id, name) VALUES ('TKL', 'Tokelau');
INSERT INTO country (id, name) VALUES ('TKM', 'Turkménistan');
INSERT INTO country (id, name) VALUES ('TLS', 'Timor-Leste');
INSERT INTO country (id, name) VALUES ('TON', 'Tonga');
INSERT INTO country (id, name) VALUES ('TTO', 'Trinité-et-Tobago');
INSERT INTO country (id, name) VALUES ('TUN', 'Tunisie');
INSERT INTO country (id, name) VALUES ('TUR', 'Turquie');
INSERT INTO country (id, name) VALUES ('TUV', 'Tuvalu');
INSERT INTO country (id, name) VALUES ('TWN', 'Taïwan');
INSERT INTO country (id, name) VALUES ('TZA', 'Tanzanie, République-Unie de');
INSERT INTO country (id, name) VALUES ('UGA', 'Ouganda');
INSERT INTO country (id, name) VALUES ('UKR', 'Ukraine');
INSERT INTO country (id, name) VALUES ('UMI', 'Îles mineures éloignées des États-Unis');
INSERT INTO country (id, name) VALUES ('URY', 'Uruguay');
INSERT INTO country (id, name) VALUES ('USA', 'États-Unis d''Amérique');
INSERT INTO country (id, name) VALUES ('UZB', 'Ouzbékistan');
INSERT INTO country (id, name) VALUES ('VAT', 'Saint-Siège');
INSERT INTO country (id, name) VALUES ('VCT', 'Saint-Vincent-et-les Grenadines');
INSERT INTO country (id, name) VALUES ('VEN', 'Venezuela');
INSERT INTO country (id, name) VALUES ('VGB', 'Vierges britanniques');
INSERT INTO country (id, name) VALUES ('VIR', 'Vierges des États-Unis');
INSERT INTO country (id, name) VALUES ('VNM', 'Viet Nam');
INSERT INTO country (id, name) VALUES ('VUT', 'Vanuatu');
INSERT INTO country (id, name) VALUES ('WLF', 'Wallis-et-Futuna');
INSERT INTO country (id, name) VALUES ('WSM', 'Samoa');
INSERT INTO country (id, name) VALUES ('YEM', 'Yémen');
INSERT INTO country (id, name) VALUES ('ZAF', 'Afrique du Sud');
INSERT INTO country (id, name) VALUES ('ZMB', 'Zambie');
INSERT INTO country (id, name) VALUES ('ZWE', 'Zimbabwe');

